"""Add decision_type index

Revision ID: a2d9f77ad266
Revises: 0003
Create Date: 2025-12-06 21:58:36.668516+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d9f77ad266'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agent_decisions_decision_type', 'agent_decisions', ['decision_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_decisions_decision_type', table_name='agent_decisions')
    # ### end Alembic commands ###
