"""add_trailing_stop_pct_to_trades

Revision ID: d71f75c90e55
Revises: a2d9f77ad266
Create Date: 2025-12-07 04:01:05.132355+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71f75c90e55'
down_revision: Union[str, None] = 'a2d9f77ad266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('trailing_stop_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'trailing_stop_pct')
    # ### end Alembic commands ###
